// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: del.proto

package del

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DelerClient is the client API for Deler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DelerClient interface {
	Do(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type delerClient struct {
	cc grpc.ClientConnInterface
}

func NewDelerClient(cc grpc.ClientConnInterface) DelerClient {
	return &delerClient{cc}
}

func (c *delerClient) Do(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/del.deler/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelerServer is the server API for Deler service.
// All implementations must embed UnimplementedDelerServer
// for forward compatibility
type DelerServer interface {
	Do(context.Context, *Req) (*Resp, error)
	mustEmbedUnimplementedDelerServer()
}

// UnimplementedDelerServer must be embedded to have forward compatible implementations.
type UnimplementedDelerServer struct {
}

func (UnimplementedDelerServer) Do(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedDelerServer) mustEmbedUnimplementedDelerServer() {}

// UnsafeDelerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DelerServer will
// result in compilation errors.
type UnsafeDelerServer interface {
	mustEmbedUnimplementedDelerServer()
}

func RegisterDelerServer(s grpc.ServiceRegistrar, srv DelerServer) {
	s.RegisterService(&Deler_ServiceDesc, srv)
}

func _Deler_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelerServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/del.deler/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelerServer).Do(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Deler_ServiceDesc is the grpc.ServiceDesc for Deler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "del.deler",
	HandlerType: (*DelerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Deler_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "del.proto",
}
