// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"YxEmr/sqd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sqd/add",
				Handler: AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sqd/del",
				Handler: DelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sqd/reg",
				Handler: RegHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sqd/cha",
				Handler: ChaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sqd/per",
				Handler: PerHandler(serverCtx),
			},
		},
	)
}
