// Code generated by goctl. DO NOT EDIT.
// Source: add.proto

package adder

import (
	"context"

	"YxEmr/sqd/rpc/add/add"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Req  = add.Req
	Resp = add.Resp

	Adder interface {
		Do(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	}

	defaultAdder struct {
		cli zrpc.Client
	}
)

func NewAdder(cli zrpc.Client) Adder {
	return &defaultAdder{
		cli: cli,
	}
}

func (m *defaultAdder) Do(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	client := add.NewAdderClient(m.cli.Conn())
	return client.Do(ctx, in, opts...)
}
