package pub

import (
	"time"
)
//go:generate goctl model mysql ddl -c -src tbzyfymx.sql -dir .
type Tzyfymx struct {
	IID       int64     `gorm:"column:IID"`
	CJZD      string    `gorm:"primary_key"`
	CZYH      string    `gorm:"column:CZYH"`
	CYLH      string    `gorm:"column:CYLH"`
	CXM       string    `gorm:"column:CXM"`
	CXB       string    `gorm:"column:CXB"`
	CNL       string    `gorm:"column:CNL"`
	IDYLB     int64     `gorm:"column:IDYLB"`
	CDYLB     string    `gorm:"column:CDYLB"`
	CSFXM     string    `gorm:"column:CSFXM"`
	IZTJZ     int64     `gorm:"column:IZTJZ"`
	IZYKS     int64     `gorm:"column:IZYKS"`
	CZYKS     string    `gorm:"column:CZYKS"`
	IZYBQ     int64     `gorm:"column:IZYBQ"`
	CZYBQ     int64     `gorm:"column:CZYBQ"`
	IZYYS     int64     `gorm:"column:IZYYS"`
	CZYYS     string    `gorm:"column:CZYYS"`
	MJE       float64   `gorm:"column:MJE"`
	MSJ       float64   `gorm:"column:MSJ"`
	MYS       float64   `gorm:"column:MYS"`
	DRQ       time.Time `gorm:"column:DRQ"`
	CBZ       string    `gorm:"column:CBZ"`
	CDW       string    `gorm:"column:CDW"`
	ISL       float64   `gorm:"column:ISL"`
	MDJ       float64   `gorm:"column:MDJ"`
	CSFXMBM   string    `gorm:"column:CSFXMBM"`
	CSFR      string    `gorm:"column:CSFR"`
	FBL       float64   `gorm:"column:FBL"`
	ITXBJ     int64     `gorm:"column:ITXBJ"`
	CTXR      string    `gorm:"column:CTXR"`
	CQMYS     string    `gorm:"column:CQMYS"`
	CJZBJ     string    `gorm:"column:CJZBJ"`
	CDJH      string    `gorm:"column:CDJH"`
	MZF       float64   `gorm:"column:MZF"`
	MYB       float64   `gorm:"column:MYB"`
	IYBBJ     int64     `gorm:"column:IYBBJ"`
	CZXKSBM   string    `gorm:"column:CZXKSBM"`
	CZXKSMC   string    `gorm:"column:CZXKSMC"`
	CYJSHR    string    `gorm:"column:CYJSHR"`
	CYJSHRGH  string    `gorm:"column:CYJSHRGH"`
	DYJSHRQ   time.Time `gorm:"column:DYJSHRQ"`
	CSSBH     string    `gorm:"column:CSSBH"`
	CSHRMC    string    `gorm:"column:CSHRMC"`
	DSHRQ     time.Time `gorm:"column:DSHRQ"`
	BSH       bool      `gorm:"column:BSH"`
	MCTZF     float64   `gorm:"column:MCTZF"`
	MBLZF     float64   `gorm:"column:MBLZF"`
	MGGZF     float64   `gorm:"column:MGGZF"`
	CSFRGH    string    `gorm:"column:CSFRGH"`
	BICUFY    bool      `gorm:"column:BICUFY"`
	CKDKSBM   string    `gorm:"column:CKDKSBM"`
	CKDKSMC   string    `gorm:"column:CKDKSMC"`
	CYJZD     string    `gorm:"column:CYJZD"`
	CCWTJ     string    `gorm:"column:CCWTJ"`
	CFYTJ     string    `gorm:"column:CFYTJ"`
	BTF       bool      `gorm:"column:BTF"`
	CZHXMBM   string    `gorm:"column:CZHXMBM"`
	CZHXMMC   string    `gorm:"column:CZHXMMC"`
	CXSE      string    `gorm:"column:CXSE"`
	DDYSJ     time.Time `gorm:"column:DDYSJ"`
	DYRQ      time.Time `gorm:"column:DYRQ"`
	CZXRBM    string    `gorm:"column:CZXRBM"`
	CZXRMC    string    `gorm:"column:CZXRMC"`
	CLJBH     string    `gorm:"column:CLJBH"`
	IGCYS     int64     `gorm:"column:IGCYS"`
	CGCYS     string    `gorm:"column:CGCYS"`
	ILB       int64     `gorm:"column:ILB"`
	CBRCW     string    `gorm:"column:CBRCW"`
	CZRHSBM   string    `gorm:"column:CZRHSBM"`
	CZRHSMC   string    `gorm:"column:CZRHSMC"`
	CBJFYBZ   string    `gorm:"column:CBJFYBZ"`
	CTXM      string    `gorm:"column:CTXM"`
	DZHRQ     time.Time `gorm:"column:DZHRQ"`
	BMZFY     bool      `gorm:"column:BMZFY"`
	CYWFYBZ   string    `gorm:"column:CYWFYBZ"`
	CSBXX     string    `gorm:"column:CSBXX"`
	CSYMD     string    `gorm:"column:CSYMD"`
	CBZ1      string    `gorm:"column:CBZ1"`
	CYJKSMC   string    `gorm:"column:CYJKSMC"`
	CYJKSBM   string    `gorm:"column:CYJKSBM"`
	BXZJYLKBX bool      `gorm:"column:BXZJYLKBX"`
	NZFBL     float64   `gorm:"column:NZFBL"`
	ctfyy     string    `gorm:"column:ctfyy"`
}
