// Code generated by goctl. DO NOT EDIT.
package types

type Addreq struct {
	Isqlx int64    `json:"isqlx"`
	Ibrlx int64    `json:"ibrlx"`
	Cbrh  string   `json:"cbrh"`
	Cmbbh string   `json:"cmbbh"`
	Cztbm []string `json:"cztbm"`
}

type Delreq struct {
	Isqlx int64  `json:"isqlx"`
	Ibrlx int64  `json:"ibrlx"`
	Cbrh  string `json:"cbrh"`
	Csqdh string `json:"csqdh"`
}

type Regreq struct {
	Ilx   int64    `json:"ilx"`
	Ibrlx int64    `json:"ibrlx"`
	Cbrh  string   `json:"cbrh"`
	Csqdh string   `json:"csqdh"`
	Cztbm []string `json:"cztbm"`
}

type Chareq struct {
	Ilx   int64    `json:"ilx"`
	Ibrlx int64    `json:"ibrlx"`
	Cbrh  string   `json:"cbrh"`
	Csfr  string   `json:"csfr"`
	Cylkh string   `json:"cylkh"`
	Csqdh string   `json:"csqdh"`
	Cztbm []string `json:"cztbm"`
}

type Perreq struct {
	Ilx   int64    `json:"ilx"`
	Ibrlx int64    `json:"ibrlx"`
	Cbrh  string   `json:"cbrh"`
	Csqdh string   `json:"csqdh"`
	Cztbm []string `json:"cztbm"`
}

type Resp struct {

}
