// Code generated by goctl. DO NOT EDIT.
// Source: per.proto

package server

import (
	"context"

	"YxEmr/sqd/rpc/per/internal/logic"
	"YxEmr/sqd/rpc/per/internal/svc"
	"YxEmr/sqd/rpc/per/per"
)

type PererServer struct {
	svcCtx *svc.ServiceContext
	per.UnimplementedPererServer
}

func NewPererServer(svcCtx *svc.ServiceContext) *PererServer {
	return &PererServer{
		svcCtx: svcCtx,
	}
}

func (s *PererServer) Do(ctx context.Context, in *per.Req) (*per.Resp, error) {
	l := logic.NewDoLogic(ctx, s.svcCtx)
	if err := l.Do(in); err != nil {
		l.Logger.Error(err)
		return &per.Resp{
			Code: 0,
			Msg:  err.Error(),
			Data: "",
		}, nil
	} else {
		return &per.Resp{
			Code: 1,
			Msg:  "ok",
			Data: "",
		}, nil
	}
}
