// Code generated by goctl. DO NOT EDIT.
// Source: per.proto

package perer

import (
	"context"

	"YxEmr/sqd/rpc/per/per"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Req  = per.Req
	Resp = per.Resp

	Perer interface {
		Do(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
		Co(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	}

	defaultPerer struct {
		cli zrpc.Client
	}
)

func NewPerer(cli zrpc.Client) Perer {
	return &defaultPerer{
		cli: cli,
	}
}

func (m *defaultPerer) Do(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	client := per.NewPererClient(m.cli.Conn())
	return client.Do(ctx, in, opts...)
}

func (m *defaultPerer) Co(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	client := per.NewPererClient(m.cli.Conn())
	return client.Co(ctx, in, opts...)
}
