// Code generated by goctl. DO NOT EDIT.
// Source: rep.proto

package server

import (
	"context"

	"YxEmr/sqd/rpc/rep/internal/logic"
	"YxEmr/sqd/rpc/rep/internal/svc"
	"YxEmr/sqd/rpc/rep/rep"
)

type ReperServer struct {
	svcCtx *svc.ServiceContext
	rep.UnimplementedReperServer
}

func NewReperServer(svcCtx *svc.ServiceContext) *ReperServer {
	return &ReperServer{
		svcCtx: svcCtx,
	}
}

func (s *ReperServer) Do(ctx context.Context, in *rep.Req) (*rep.Resp, error) {
	l := logic.NewDoLogic(ctx, s.svcCtx)
	_,err := l.Do(in)
	if err != nil {
		l.Logger.Error(err)
	}
	return &rep.Resp{},err
}
