// Code generated by goctl. DO NOT EDIT.
// Source: add.proto

package server

import (
	"context"

	"YxEmr/sqd/rpc/add/add"
	"YxEmr/sqd/rpc/add/internal/logic"
	"YxEmr/sqd/rpc/add/internal/svc"
)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	add.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) Do(ctx context.Context, in *add.Req) (*add.Resp, error) {
	l := logic.NewDoLogic(ctx, s.svcCtx)
	if csqdh, err := l.Do(in); err != nil {
		l.Logger.Error(err)
		return &add.Resp{
			Code: 0,
			Msg:  err.Error(),
			Data: "",
		}, nil
	} else {
		return &add.Resp{
			Code: 1,
			Msg:  "成功",
			Data: csqdh,
		}, nil
	}
}
